3038 vuetify and vuetify tests modules (#3195)
* Initial commit for vuetify tests project

* Added whitespaces

* Added whitespaces to log4j2.xml

* Fixed versions, added general suite

* Switched to general suite. Fixed versions params.

* del one more scope

* Run tests on PR to Vuetify

* +all jdk (just to be sure)

Co-authored-by: Igor.Gaiduk <igor.gaiduk@syngenta.com>
Co-authored-by: Natalia_Pozhidaeva <Natalia_Pozhidaeva@epam.com>

diff --git a/.github/workflows/debug.yml b/.github/workflows/debug.yml
--- a/.github/workflows/debug.yml
+++ b/.github/workflows/debug.yml
@@ -1,7 +1,7 @@
 # This workflow will build a Java project with Maven
 # For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
 
-name: JDI auto-tests debug
+name: JDI auto-tests debug Vuetify tests
 env:
     CHROME_PROPERTIES: "chrome.properties"
     FIREFOX_PROPERTIES: "ff.properties"
@@ -21,13 +21,17 @@ env:
     EXAMPLES_PROPERTY: "test-examples/jdi-light-examples"
     PERFORMANCE: "jdi-performance"
     PERFORMANCE_PROPERTY: "test-examples/jdi-performance"
+    VUETIFY_TESTS: "jdi-light-vuetify-tests"
     CHROME_ARGS: "--no-sandbox --headless --disable-dev-shm-usage --disable-gpu --window-size=1920,1080"
     FIREFOX_ARGS: "-headless"
     ALLURE_VERSION: "2.13.8"
 
 on:
   push:
-    branches: [ fix_branch_for_some_tests ] # ENTER branch name there
+    branches: [ Vuetify ] # ENTER branch name there
+  pull_request:
+    branches:
+      - Vuetify
 # !!!! PLEASE do not change this file in master, as it's only template for branch debug in GitHub Actions
 
 jobs:
@@ -36,7 +40,7 @@ jobs:
     runs-on: ubuntu-18.04
     strategy:
       matrix:
-        java: [8] # by default we use only 8. can be changed to any, the full list is [8, 9, 10, 11, 12, 13]
+        java: [8, 9, 10, 11, 12, 13, 14] # by default we use only 8. can be changed to any, the full list is [8, 9, 10, 11, 12, 13]
 
     steps:
     - uses: actions/checkout@v2
@@ -82,6 +86,8 @@ jobs:
         echo arguments=$FIREFOX_ARGS > "./${EXAMPLES_PROPERTY}/src/test/resources/${FIREFOX_PROPERTIES}"
         echo arguments=$CHROME_ARGS > "./${PERFORMANCE_PROPERTY}/src/test/resources/${CHROME_PROPERTIES}"
         echo arguments=$FIREFOX_ARGS > "./${PERFORMANCE_PROPERTY}/src/test/resources/${FIREFOX_PROPERTIES}"
+        echo arguments=$CHROME_ARGS > "./${VUETIFY_TESTS}/src/test/resources/${CHROME_PROPERTIES}"
+        echo arguments=$FIREFOX_ARGS > "./${VUETIFY_TESTS}/src/test/resources/${FIREFOX_PROPERTIES}"
 
     - name: Compile jdi code
       id: jdi-compile
@@ -92,11 +98,11 @@ jobs:
 # !!! select required project you debug to save time.
 # All other projects you can delete or comment.
 
-    - name: Tests BDD
-      if: ${{ steps.jdi-compile.outcome == 'success' }}
-      timeout-minutes: 90 # prevent blocking
-      run: |
-          mvn verify $WITH_PARAMS -DCucumber.options="--tags ~@ignore_for_firefox" -Dchrome.capabilities.path=${CHROME_PROPERTIES} -Dff.capabilities.path=${FIREFOX_PROPERTIES} -pl $GROUP_ID:$BDD_TESTS --fail-at-end
+#    - name: Tests BDD
+#      if: ${{ steps.jdi-compile.outcome == 'success' }}
+#      timeout-minutes: 90 # prevent blocking
+#      run: |
+#          mvn verify $WITH_PARAMS -DCucumber.options="--tags ~@ignore_for_firefox" -Dchrome.capabilities.path=${CHROME_PROPERTIES} -Dff.capabilities.path=${FIREFOX_PROPERTIES} -pl $GROUP_ID:$BDD_TESTS --fail-at-end
 
 #####  Example for original allure data upload
 #    - name: 'Upload BDD results'
@@ -106,10 +112,10 @@ jobs:
 #        path: ./${BDD_TESTS}/target/allure-results/
 #        retention-days: 1
 
-    - name: Tests bootstrap Unit
-      if: ${{ steps.jdi-compile.outcome == 'success' }}
-      timeout-minutes: 90 # prevent blocking
-      run: mvn verify $WITH_PARAMS -Dchrome.capabilities.path=${CHROME_PROPERTIES} -Dff.capabilities.path=${FIREFOX_PROPERTIES} -pl $GROUP_ID:$BOOTSTRAP_TESTS --fail-at-end
+#    - name: Tests bootstrap Unit
+#      if: ${{ steps.jdi-compile.outcome == 'success' }}
+#      timeout-minutes: 90 # prevent blocking
+#      run: mvn verify $WITH_PARAMS -Dchrome.capabilities.path=${CHROME_PROPERTIES} -Dff.capabilities.path=${FIREFOX_PROPERTIES} -pl $GROUP_ID:$BOOTSTRAP_TESTS --fail-at-end
 
 #    - name: Run tests - Angular Unit tests
 #      if: ${{ steps.jdi-compile.outcome == 'success' }}
@@ -126,20 +132,27 @@ jobs:
 #      timeout-minutes: 90 # prevent blocking
 #      run: mvn verify $WITH_PARAMS -Dchrome.capabilities.path=${CHROME_PROPERTIES} -Dff.capabilities.path=${FIREFOX_PROPERTIES} $COMPLEX -pl $GROUP_ID:$ANGULAR_TESTS --fail-at-end
 
-    - name: Run tests - HTML
-      if: ${{ steps.jdi-compile.outcome == 'success' }}
-      timeout-minutes: 90 # prevent blocking
-      run: mvn verify $WITH_PARAMS -Dchrome.capabilities.path=${CHROME_PROPERTIES} -Dff.capabilities.path=${FIREFOX_PROPERTIES} -pl $GROUP_ID:$HTML_TESTS --fail-at-end
+#    - name: Run tests - HTML
+#      if: ${{ steps.jdi-compile.outcome == 'success' }}
+#      timeout-minutes: 90 # prevent blocking
+#      run: mvn verify $WITH_PARAMS -Dchrome.capabilities.path=${CHROME_PROPERTIES} -Dff.capabilities.path=${FIREFOX_PROPERTIES} -pl $GROUP_ID:$HTML_TESTS --fail-at-end
 
-    - name: Run tests - Test Examples
-      if: ${{ steps.jdi-compile.outcome == 'success' }}
-      timeout-minutes: 90 # prevent blocking
-      run: mvn verify $WITH_PARAMS -Dchrome.capabilities.path=${CHROME_PROPERTIES} -Dff.capabilities.path=${FIREFOX_PROPERTIES} -pl $GROUP_ID:$EXAMPLES --fail-at-end
+#    - name: Run tests - Test Examples
+#      if: ${{ steps.jdi-compile.outcome == 'success' }}
+#      timeout-minutes: 90 # prevent blocking
+#      run: mvn verify $WITH_PARAMS -Dchrome.capabilities.path=${CHROME_PROPERTIES} -Dff.capabilities.path=${FIREFOX_PROPERTIES} -pl $GROUP_ID:$EXAMPLES --fail-at-end
 
-    - name: Run tests - Performance
+#    - name: Run tests - Performance
+#      if: ${{ steps.jdi-compile.outcome == 'success' }}
+#      timeout-minutes: 90 # prevent blocking
+#      run: mvn verify $WITH_PARAMS -Dchrome.capabilities.path=${CHROME_PROPERTIES} -Dff.capabilities.path=${FIREFOX_PROPERTIES} -pl $GROUP_ID:$PERFORMANCE --fail-at-end
+
+    - name: Run tests - Vuetify
+      id: tests-vuetify
       if: ${{ steps.jdi-compile.outcome == 'success' }}
-      timeout-minutes: 90 # prevent blocking
-      run: mvn verify $WITH_PARAMS -Dchrome.capabilities.path=${CHROME_PROPERTIES} -Dff.capabilities.path=${FIREFOX_PROPERTIES} -pl $GROUP_ID:$PERFORMANCE --fail-at-end
+      continue-on-error: true
+      timeout-minutes: 30 # prevent blocking
+      run: mvn verify $WITH_PARAMS -Dchrome.capabilities.path=${CHROME_PROPERTIES} -Dff.capabilities.path=${FIREFOX_PROPERTIES} -pl $GROUP_ID:$VUETIFY_TESTS --fail-at-end
 
     - name: Collect reports
       if: ${{ steps.jdi-compile.outcome == 'success' }}
@@ -159,3 +172,9 @@ jobs:
         name: allure-report-jdk${{ matrix.java }}
         path: ./allure-report.zip
         retention-days: 1
+
+    - name: Check Vuetify tests are passed
+      if: ${{ steps.tests-vuetify.outcome != 'success'}}
+      run: |
+        echo Vuetify tests result: ${{ steps.tests-vuetify.outcome }}
+        exit 1
