fix few issues

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,15 +17,15 @@ env:
     BDD_TESTS: "jdi-bdd-tests"
     BOOTSTRAP_TESTS: "jdi-light-bootstrap-tests"
     HTML_TESTS: "jdi-light-html-tests"
-    ANGULAR_TESTS: "jdi-light-angular-tests"
-    ANGULAR_TESTS_WITH_MOCKS: "jdi-light-angular-tests-with-mocks"
+    # ANGULAR_TESTS: "jdi-light-angular-tests"
+    # ANGULAR_TESTS_WITH_MOCKS: "jdi-light-angular-tests-with-mocks"
     EXAMPLES: "jdi-light-examples"
     EXAMPLES_PROPERTY: "test-examples/jdi-light-examples"
     PERFORMANCE: "jdi-performance"
     PERFORMANCE_PROPERTY: "test-examples/jdi-performance"
     CHROME_ARGS: "--no-sandbox --headless --disable-dev-shm-usage --disable-gpu --window-size=1920,1080"
     FIREFOX_ARGS: "-headless"
-    ALLURE_VERSION: "2.7.0"
+    ALLURE_VERSION: "2.13.8"
 
 on:
   push:
@@ -86,8 +86,6 @@ jobs:
         echo arguments=$FIREFOX_ARGS > "./${BDD_TESTS}/src/test/resources/${FIREFOX_PROPERTIES}"
         echo arguments=$CHROME_ARGS > "./${BOOTSTRAP_TESTS}/src/test/resources/${CHROME_PROPERTIES}"
         echo arguments=$FIREFOX_ARGS > "./${BOOTSTRAP_TESTS}/src/test/resources/${FIREFOX_PROPERTIES}"
-        echo arguments=$CHROME_ARGS > "./${ANGULAR_TESTS}/src/test/resources/${CHROME_PROPERTIES}"
-        echo arguments=$FIREFOX_ARGS > "./${ANGULAR_TESTS}/src/test/resources/${FIREFOX_PROPERTIES}"
         echo arguments=$CHROME_ARGS > "./${HTML_TESTS}/src/test/resources/${CHROME_PROPERTIES}"
         echo arguments=$FIREFOX_ARGS > "./${HTML_TESTS}/src/test/resources/${FIREFOX_PROPERTIES}"
         echo arguments=$CHROME_ARGS > "./${EXAMPLES_PROPERTY}/src/test/resources/${CHROME_PROPERTIES}"
@@ -99,7 +97,7 @@ jobs:
       id: jdi-compile
       run: mvn -ntp install -DskipTests
 
-  # ========== steps before are needed for all tasks ==================
+  # ========== steps before required for all tasks ==================
 
     - name: Tests BDD
       id: tests-bdd
@@ -145,18 +143,18 @@ jobs:
 #    - name: Kill Chrome
 #      run: pkill -f "chrome"
 
-    - name: Run tests - Angular Common tests
-      id: tests-angular-common
-      if: steps.jdi-compile.outcome == 'success'
-      timeout-minutes: 30 # prevent blocking
-      continue-on-error: true
-      run: mvn verify $WITH_PARAMS -Dchrome.capabilities.path=${CHROME_PROPERTIES} -Dff.capabilities.path=${FIREFOX_PROPERTIES} $COMMON -pl $GROUP_ID:$ANGULAR_TESTS --fail-at-end
-
-    - name: Check Chrome
-      run: ps -aux | grep chrome
-
-    - name: Kill Chrome
-      run: pkill -f "chrome"
+#    - name: Run tests - Angular Common tests
+#      id: tests-angular-common
+#      if: steps.jdi-compile.outcome == 'success'
+#      timeout-minutes: 30 # prevent blocking
+#      continue-on-error: true
+#      run: mvn verify $WITH_PARAMS -Dchrome.capabilities.path=${CHROME_PROPERTIES} -Dff.capabilities.path=${FIREFOX_PROPERTIES} $COMMON -pl $GROUP_ID:$ANGULAR_TESTS --fail-at-end
+#
+#    - name: Check Chrome
+#      run: ps -aux | grep chrome
+#
+#    - name: Kill Chrome
+#      run: pkill -f "chrome"
 
 #    - name: Run tests - Angular Complex tests
 #      id: tests-angular-complex
@@ -247,15 +245,15 @@ jobs:
         echo Example tests result: ${{ steps.tests-examples.outcome }}
         exit 1
 
-    - name: Check angular tests are passed
-      if: ${{ steps.tests-angular-common.outcome != 'success' }}
+#    - name: Check angular tests are passed
+#      if: ${{ steps.tests-angular-common.outcome != 'success' }}
 # for full angular should be
 #      if: ${{ steps.tests-angular-unit.outcome != 'success' || steps.tests-angular-common.outcome != 'success' || steps.tests-angular-complex.outcome != 'success' }}
 #        echo Angular Complex tests result: ${{ steps.tests-angular-complex.outcome }}
 #        echo Angular Unit tests result: ${{ steps.tests-angular-unit.outcome }}
-      run: |
-        echo Angular Common tests result: ${{ steps.tests-angular-common.outcome }}
-        exit 1
+#      run: |
+#        echo Angular Common tests result: ${{ steps.tests-angular-common.outcome }}
+#        exit 1
 
     - name: Check performance tests are passed
       if: ${{ steps.tests-html-perf.outcome != 'success' || steps.tests-perf.outcome != 'success' }}
